mod 'puppetlabs/apache', '1.1.1'
mod 'puppetlabs/concat', '1.1.0'
mod 'puppetlabs/firewall', '1.1.3'
mod 'puppetlabs/inifile', '1.1.3'
mod 'puppetlabs/postgresql', '3.4.1'
mod 'puppetlabs/puppetdb', '3.0.1'
mod 'puppetlabs/stdlib', '4.3.2'
mod 'stahnma/epel', '0.0.6'
mod 'stephenrjohnson/puppet', '0.0.23'
mod 'hostnamefacts',
  :git => 'https://github.com/geogdog/puppet-hostnamefacts',
  :tag => 'v0.1.5'
